Remove deprecated CrafterCMSNext references
craftercms/bulkedit-plugin pull request #4
Opened 2024-07-23 05:42 UTC by phuongnq

This updates the plugin to use `craftercms` references which is the replacement for `CrafterCMSNext` in 4.2.0
@russdanner FYI

2024-07-23 12:30 UTC, sumerjabri commented
@phuongnq if we merge this, will this plugin work for older versions? If not, we must update the compatibility list.

2024-07-23 12:30 UTC, sumerjabri requested changes
See note

2024-07-24 08:14 UTC, phuongnq commented
@sumerjabri Per discussion with @russdanner , I dropped the support for 4.0.x. Also tested this with 4.1.0 that the new variable `craftercms` available and the plugin works as expected!

2024-07-24 14:44 UTC, sumerjabri approved these changes

2024-07-24 14:44 UTC, merged